USE TSQLV4
GO

CREATE TYPE Exemplo FROM VARCHAR(50) NOT NULL;
GO

CREATE TABLE Sales.Exemplo
(
  Id    INT PRIMARY KEY IDENTITY(1, 1), 
  Nome  Exemplo NOT NULL
);

INSERT INTO Sales.Exemplo VALUES ('Allan 1');
INSERT INTO Sales.Exemplo VALUES ('KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK')
SELECT * FROM Sales.Exemplo;
GO


CREATE TYPE dbo.ExemploTableType AS TABLE   
    ( Nome      VARCHAR(50) NOT NULL 
    , Idade     INT         NOT NULL); 
GO

DECLARE @ExemploType AS dbo.ExemploTableType
INSERT INTO @ExemploType VALUES ('Allan', 20);

SELECT * FROM @ExemploType;

/*
DROP TABLE Sales.Exemplo
DROP TYPE Exemplo
DROP TYPE ExemploTableType
*/